#define _STLP_PLATFORM "Xbox 360"
#define _STLP_BIG_ENDIAN 1
#define _STLP_NATIVE_INCLUDE_PATH ../xbox
#define _STLP_NATIVE_C_INCLUDE_PATH ../xbox
#define _STLP_NATIVE_CPP_C_INCLUDE_PATH ../xbox
#define _STLP_NO_USING_FOR_GLOBAL_FUNCTIONS
#undef _STLP_LONG_LONG
